//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.11 at 10:57:16 PM CEST 
//


package bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for competenceDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="competenceDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="titreCompetence" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="categorie" type="{http://www.example.org/schemaCV}categorieType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "competenceDetailType", propOrder = {
    "titreCompetence",
    "categorie"
})
public class CompetenceDetailType {

    @XmlElement(required = true)
    protected String titreCompetence;
    @XmlElement(required = true)
    protected List<CategorieType> categorie;

    /**
     * Gets the value of the titreCompetence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitreCompetence() {
        return titreCompetence;
    }

    /**
     * Sets the value of the titreCompetence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitreCompetence(String value) {
        this.titreCompetence = value;
    }

    /**
     * Gets the value of the categorie property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categorie property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategorie().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link bean.CategorieType }
     * 
     * 
     */
    public List<CategorieType> getCategorie() {
        if (categorie == null) {
            categorie = new ArrayList<CategorieType>();
        }
        return this.categorie;
    }

}
