//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.11 at 10:57:16 PM CEST 
//


package bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cv }
     * 
     */
    public Cv createCv() {
        return new Cv();
    }

    /**
     * Create an instance of {@link IdentiteType }
     * 
     */
    public IdentiteType createIdentiteType() {
        return new IdentiteType();
    }

    /**
     * Create an instance of {@link FonctionType }
     * 
     */
    public FonctionType createFonctionType() {
        return new FonctionType();
    }

    /**
     * Create an instance of {@link CompetenceType }
     * 
     */
    public CompetenceType createCompetenceType() {
        return new CompetenceType();
    }

    /**
     * Create an instance of {@link ExperienceType }
     * 
     */
    public ExperienceType createExperienceType() {
        return new ExperienceType();
    }

    /**
     * Create an instance of {@link CompetenceDetailType }
     * 
     */
    public CompetenceDetailType createCompetenceDetailType() {
        return new CompetenceDetailType();
    }

    /**
     * Create an instance of {@link CategorieType }
     * 
     */
    public CategorieType createCategorieType() {
        return new CategorieType();
    }

    /**
     * Create an instance of {@link AdresseType }
     * 
     */
    public AdresseType createAdresseType() {
        return new AdresseType();
    }

}
